FROM ubuntu:20.04

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install --no-install-recommends --yes \
        gcc-arm-linux-gnueabihf \
        git \
        libc6-dev-armhf-cross \
        linux-headers-generic \
        make
