#!/bin/bash

case "$1" in
  start)
    echo "Starting scwrapper..."
    start-stop-daemon -S -x "/usr/bin/scwrapper" -p "/var/run/scwrapper.pid"
    ;;
  stop)
    echo "Stopping scwrapper..."
    start-stop-daemon -K -x "/usr/bin/scwrapper" -p "/var/run/scwrapper.pid" -o
    ;;
  restart)
    "$0" stop && sleep 5 && "$0" start
    ;;
  reload|force-reload)
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|force-reload}"
    exit 1
    ;;
esac
